### ISSUE TITLE
Sends unsupported referrer to the Support API

### ISSUE THREAD

**Issue by cbaines** [alphagov/feedback#202]
Support API only supports URL referrers, but Feedback is capable of currently sending others, e.g. `android-app://com.google.android.googlequicksearchbox/https/www.google.com`.

Errbit:
 - https://errbit.publishing.service.gov.uk/apps/5319fd4f0da11511b00017c3/problems/58f5f6766578636169e62800

**Comment by tijmenb** [comment]
Since we've moved to Sentry we've not seen these errors anymore.
